### ISSUE TITLE
Fine-Tuning GPT 3.5

### ISSUE THREAD

**Issue by JP-Leite** [WenjinW/LATIN-Prompt#2]
First off, wanted to say that this is a very interesting way to tackle the issue of layout within a prompt.

Do you have any plans to experiment with fine-tuning GPT3.5 Turbo with the DocVQA dataset? Would be interesting to see if results improve from zero-shot.

**Comment by WenjinW** [comment]
This is an interesting suggestion, but the cost of fine-tuning GPT3.5 Turbo is too expensive. We will consider conducting this experiment on LLaMA2-Chat instead.
