### ISSUE TITLE
VQA groups

### ISSUE THREAD

**Issue by ronenroi** [WenjinW/LATIN-Prompt#3]
Thank you for sharing the code and for the nice paper.
Can you direct me to where I can find the group devision for InfographicVQA dataset? (table 5)
If it is not public yet, can you make it available?

**Comment by WenjinW** [comment]
You can upload the test result file to the official leaderboard, and it will be automatically grouped. You can find more details about it [here](https://rrc.cvc.uab.es/?ch=17&com=evaluation&task=3).
