### ISSUE TITLE
Latin-prompt

### ISSUE THREAD

**Issue by Jordy-VL** [WenjinW/LATIN-Prompt#4]
One of the innovations brought by your work is to have structure-preserving OCR (implemented as whitespacing and newlines) for the documents as part of the prompts. 

From the first Figure in the paper I reckoned you gave literally the string "__5___" to indicate 5 whitespaces. What is now the most correct way? Doesn't the tokenizer of the LLM just filter away multiple whitespaces?

**Comment by WenjinW** [comment]
That's a good question. In fact, the tokenizer is aware of the number of spaces. Here is a simple example.

<img width="1074" alt="image" src="https://github.com/WenjinW/LATIN-Prompt/assets/30342227/b2db05db-7b6f-441f-ba88-3563f7b504fd">

I hope this is helpful for you.
